version: '3'

services:
  app_tests:
    container_name: app_tests
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/app/src/app/
    depends_on:
      - postgres_test
    networks:
      - fullstack_test

  postgres_test:
    image: postgres:latest
    container_name: full_db_test
    environment:
      - POSTGRES_USER=${TEST_DB_USER}  
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - fullstack_test
  
  pgadmin_test:
    image: dpage/pgadmin4
    container_name: pgadmin_test
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL_TEST}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD_TEST}
    depends_on:
      - postgres_test
    ports:
      - "5555:80"
    restart: unless-stopped

volumes:
  api_test:
  database_postgres_test:

networks:
  fullstack_test:
    driver: bridge
